### ISSUE TITLE
Yii::log don't work in worker class with Yii  1.1.16

### ISSUE THREAD

**Issue by mmdtl** [rolies106/yii-resque#25]
I try to use the own log class of YII , but it does't work. I have add "log" to preload of  my console.php. How could I use it?

**Comment by rolies106** [comment]
I think that is normal, you need to load log component before you use it, or can you post your script? and error message if any.

**Comment by mmdtl** [comment]
Resolved by add below code before use Yii::log
```
Yii::getLogger()->autoDump = true;
Yii::getLogger()->autoFlush = 1;
```
Seems Yii only flush log to file on some event default. Thank you for your response.
